### ISSUE TITLE
urllib error in geoshp preview

### ISSUE THREAD

**Issue by tcnichol** [clowder-framework/extractors-geo#19]
Errors with urllib for urlencode and urlopen.

**Comment by tcnichol** [comment]
If someone can give me access to push a branch and create a pull request, I believe I've fixed this one.

**Comment by robkooper** [comment]
@tcnichol do you still have this fix?

**Comment by tcnichol** [comment]
I believe it was merged in with this pull request. It might have been linked to other issues. 

https://github.com/clowder-framework/extractors-geo/pull/20
